/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test

class FileIndexerTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
//        val classUnderTest = Library()
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
